name: CI & SonarQube Analysis
on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *' # 08:00 KST every day
env:
  CI: ''
jobs:
  ci:
    runs-on: ubuntu-latest
    name: 'Build test'
    steps:
      - name: checkout@v3
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Cache node_modules 🚀
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{runner.OS}}-build-${{hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{ runner.OS }}-build-${{ runner.OS }}-
      - name: Install and Build
        run: |
          yarn install
          yarn run build
