name: CI
on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *' # 08:00 KST every day

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    name: 'Test and Build'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn run test

      - name: Build
        run: yarn run build
