name: 운영환경 - 배포
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  CI: ''
jobs:
  ci:
    runs-on: ubuntu-latest
    name: 'Build test'
    steps:
      - name: checkout@v3
        uses: actions/checkout@v3

      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Cache node_modules 🚀
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{runner.OS}}-build-${{hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{ runner.OS }}-build-${{ runner.OS }}-
      - name: Install and Build
        run: |
          yarn install
          yarn run build

  deploy:
    needs:
      - ci
    runs-on: ubuntu-latest
    name: 'Deploy to Netlify'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_PROD}}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_PROD }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN_PROD", "NETLIFY_SITE_ID_PROD"]'
